### ISSUE TITLE
recv fails with buf == null

### ISSUE THREAD

**Issue by coffeeowl** [bnoordhuis/node-unix-dgram#21]
I am using ain2 with unix socket and recently I have got an error:

> TypeError: Cannot read property 'length' of null
>   at Socket.recv (/usr/lib/node_modules/my_project/node_modules/ain2/node_modules/unix-dgram/lib/unix_dgram.js:27:14)

Seems like buf sometimes can be null, I don't know why, if that is an expected behaviour or not, maybe the solution is just to check if buf is null or not.

**Comment by bnoordhuis** [comment]
I think it's because of a missing error check.  Can you try this patch?

```diff
diff --git a/lib/unix_dgram.js b/lib/unix_dgram.js
index 1f72a78..d4f8808 100644
--- a/lib/unix_dgram.js
+++ b/lib/unix_dgram.js
@@ -22,7 +22,11 @@ function errnoException(errorno, syscall) {
 }


-function recv(status, buf, path) {
+function recv(err, buf, path) {
+  if (err < 0) {
+    this.emit('error', errnoException(err, 'recvmsg'));
+    return;
+  }
   var rinfo = {
     size: buf.length,
     address: {},
```

I'd be curious to know what error you get because I can't really think of plausible recvmsg failures (except, maybe, EAGAIN.)  On what platform is this?

**Comment by coffeeowl** [comment]
I can try, but the problem is that I can't reproduce it, it happened just once yesterday but the code has been running for months and curently there are no more errors like that.

**Comment by bnoordhuis** [comment]
This issue has been open for over 4 years with no progress so I'm going to go ahead and close it.
