### ISSUE TITLE
Fails to build with iojs v2.0.0

### ISSUE THREAD

**Issue by baseonmars** [bnoordhuis/node-unix-dgram#23]
Hi,

I'm having some issues building this package with iojs v2.0.0

npm-debug.log: https://gist.github.com/baseonmars/f69b7eb25ce92e865a9f

I've done a little digging and it looks like the main issue is the version of nan (needs to be v 1.8.4 for V8 4.2 compat).

There's also a warning with node:FatalException from the unix-dgram code it's self.

I've attempted a patch, unfortunatly it breaks backwards compatibility, my C++ knowledge is close to 0, but I've included a link to the branch for reference: https://github.com/baseonmars/node-unix-dgram/tree/iojs-v2.0.0

*edit:* Just noticed https://github.com/iojs/nan/pull/327 which could be used instead of node:FatalException when merged and released.

**Comment by bnoordhuis** [comment]
Fixed by d071e00 and 314858e and released as v0.2.0.  Thanks for the bug report.

**Comment by baseonmars** [comment]
Thanks, you're awesome!
