### ISSUE TITLE
nan update

### ISSUE THREAD

**Issue by Trixt0r** [bnoordhuis/node-unix-dgram#26]
Hi, can someone please update the nan version to at least 1.8.2, so it can be used with electron?

- Trixt0r

**Comment by santigimeno** [comment]
@Trixt0r Can't you already use the module with 1.8.2 or newer? In my machine it installs the latest 1.8.x nan version.
```
 $ npm install unix-dgram
|
> unix-dgram@0.2.1 install /tmp/node_modules/unix-dgram
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
  SOLINK_MODULE(target) Release/obj.target/unix_dgram.node
  COPY Release/unix_dgram.node
make: Leaving directory `/tmp/node_modules/unix-dgram/build'
unix-dgram@0.2.1 node_modules/unix-dgram
├── bindings@1.1.1
└── nan@1.8.4
```

**Comment by Trixt0r** [comment]
I see, the problem lies behind another module, which has dependencies on unix-dgram.
The weird thing about this is that removing the version prefix `~` in its package.json solved it.
