### ISSUE TITLE
Buffer limited to 2048 on Mac OS

### ISSUE THREAD

**Issue by jbdemonte** [bnoordhuis/node-unix-dgram#38]
Hi,

I'm facing a strange limitation I failed to bypass, on my mac, this code fail when the Buffer length is over 2048 with error -40 while on debian it fails over 212960 with error -90

    var fs = require('fs');
    var socketPath = __dirname + '/test.socket';
    
    var unix = require('unix-dgram');
    var server = unix.createSocket('unix_dgram', function(buf) {
      console.log('received ' + buf);
      server.close();
      fs.unlink(socketPath);
    });
    server.bind(socketPath);
    
    var len = 2049;
    message = Buffer((new Array(len + 1)).join('A'));
    var client = unix.createSocket('unix_dgram');
    
    client.on('error', function (err) {
      console.error(err);
      server.close();
      fs.unlink(socketPath);
    });
    
    client.send(message, 0, message.length, socketPath);
    client.close();

I didn't found any info on these limitation, do you have any information about this?

**Comment by bnoordhuis** [comment]
That error code is EMSGSIZE, the numbers are different on different platforms.

Because datagram sockets are message oriented, you are limited to the maximum message size, which is fairly small on OS X (as you discovered.)

**Comment by jbdemonte** [comment]
Thanks, do you know if it is updatable on hot using node?

**Comment by bnoordhuis** [comment]
I'm afraid I don't understand your question; "updatable on hot using node"?

**Comment by jbdemonte** [comment]
:D sorry
I mean, is there a way to increase it in my node code?

**Comment by bnoordhuis** [comment]
Unfortunately no, it's a limit of the operating system.

**Comment by jbdemonte** [comment]
:/ 
btw, thanks a lot for your help
