### ISSUE TITLE
Sending data in loop fails

### ISSUE THREAD

**Issue by jbdemonte** [bnoordhuis/node-unix-dgram#39]
Sending data in loop fails,
It seems to be required to add en arbitrary setTimeout to delay the write. I also tried to use process.nextTick, but it didn't fix)

(fyi, on my side, I'm using a python code for the server and get the same fails)

server.js

      var unix = require('unix-dgram');
      var fs = require('fs');
      var socketPath = __dirname + '/test.socket';
      
      if (fs.existsSync(socketPath)) {
        fs.unlink(socketPath);
      }
      
      var server = unix.createSocket('unix_dgram', function (buf) {
        console.log('received: ' + buf);
      });
      
      server.bind(socketPath);
      
client.js

    var unix = require('unix-dgram');
    var client = unix.createSocket('unix_dgram');
    var socketPath = __dirname + '/test.socket';
    
    client.on('error', function (err) {
      console.error(err);
      client.close();
    });
    
    var i=0, message;
    
    /**/
    for (i = 0; i < 1000; i++) {
      message = Buffer.from('message ' + i);
      client.send(message, 0, message.length, socketPath);
    }
    client.close();
    /**/
    
    
    /** /
    // this code works thanks to the setTimeout
    function send() {
      i++;
      var message = Buffer.from('message ' + i);
      client.send(message, 0, message.length, socketPath);
      if (i < 1000) {
        setTimeout(send, 10);
      } else {
        client.close();
      }
    }
    send();
    /**/

Here is the error on my mac laptop:

jbd:~/git/lala$ node client.js 
{ [Error: send -55] code: -55, errno: -55, syscall: 'send' }
{ [Error: send -9] code: -9, errno: -9, syscall: 'send' }
Assertion failed: (iter != watchers.end()), function StopWatcher, file ../src/unix_dgram.cc, line 166.

Here is the error on my debian server:

    jbd@beta:~/test_socket$ node client.js
    { Error: send -11
      at errnoException (/home/jbd/test_socket/node_modules/unix-dgram/lib/unix_dgram.js:18:11)
      at Socket.send (/home/jbd/test_socket/node_modules/unix-dgram/lib/unix_dgram.js:93:17)
      at Object.<anonymous> (/home/jbd/test_socket/client.js:15:10)
      at Module._compile (module.js:571:32)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.runMain (module.js:605:10)
      at run (bootstrap_node.js:420:7) code: -11, errno: -11, syscall: 'send' }
    { Error: send -9
      at errnoException (/home/jbd/test_socket/node_modules/unix-dgram/lib/unix_dgram.js:18:11)
      at Socket.send (/home/jbd/test_socket/node_modules/unix-dgram/lib/unix_dgram.js:93:17)
      at Object.<anonymous> (/home/jbd/test_socket/client.js:15:10)
      at Module._compile (module.js:571:32)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.runMain (module.js:605:10)
      at run (bootstrap_node.js:420:7) code: -9, errno: -9, syscall: 'send' }
    node: ../src/unix_dgram.cc:166: void {anonymous}::StopWatcher(int): Assertion `iter != watchers.end()' failed.

**Comment by bnoordhuis** [comment]
-9 is EBADF, -11 is EAGAIN on Linux, -55 is ENOBUFS on OS X.  I should probably add string error names but in the mean time consult errno.h on your system; the error code is the negated errno.

EBADF means you are trying to send on a socket you closed earlier.  ENOBUFS means you've exhausted the kernel's resources and need to back off.

EAGAIN should have been handled by unix-dgram, I think.  @santigimeno Why is it that send() starts the poll watcher but sendto() simply returns the error?

**Comment by santigimeno** [comment]
>  @santigimeno Why is it that send() starts the poll watcher but sendto() simply returns the error?

@bnoordhuis IIRC `send()` just adds the `UV_WRITABLE` flag to the handle. The socket should already be watching for [`UV_READABLE`](https://github.com/bnoordhuis/node-unix-dgram/blob/master/src/unix_dgram.cc#L215) [events](https://github.com/bnoordhuis/node-unix-dgram/blob/master/src/unix_dgram.cc#L143-L155). `bindings.send()` should only be used for _connected_ sockets and the `UV_WRITABLE` flag is needed for the `congestion` and `writable` events, see: https://github.com/bnoordhuis/node-unix-dgram#socketconnectremote_path.

> EAGAIN should have been handled by unix-dgram

AFAICT, `EAGAIN` was never handled with _non-connected_ sockets. In fact, that's one of the reasons I added the __connected__ sockets functionality.

**Comment by santigimeno** [comment]
For this issue I would use code similar to the one in https://github.com/bnoordhuis/node-unix-dgram#socketsendbuf-callback that allows implementing some congestion control.

**Comment by jbdemonte** [comment]
I tried the example code you just linked, but the writable / congestion events are never received on mac os

    var unix = require('unix-dgram');
    var client = unix.createSocket('unix_dgram');
    var socketPath = __dirname + '/test.socket';

    client.on('error', function (err) {
      console.error(err);
      client.close();
    });

    client.on('congestion', function() {
      console.log('congestion * * * * * * *');
      /* The server is not accepting data */
    });

    client.on('writable', function() {
      console.log('writable * * * * * * *');
      /* The server can accept data */
    });

    client.on('connect', function() {
      console.log('connected');
      for (var i = 0; i < 1000; i++) {
        var message = 'message ' + i;
        console.log('sending ' + message);
        client.send(Buffer.from(message));
      }
    });

    client.connect(socketPath);


Using this test code, here are the logs:

    ...
    sending message 64
    sending message 65
    { [Error: send -55] code: -55, errno: -55, syscall: 'send' }
    sending message 66
    { [Error: send -9] code: -9, errno: -9, syscall: 'send' }
    Assertion failed: (iter != watchers.end()), function StopWatcher, file ../src/unix_dgram.cc, line 166.
    Abort trap: 6

On Debian, the events are well received

**Comment by santigimeno** [comment]
@jbdemonte can you try the following patch?
```
diff --git a/src/unix_dgram.cc b/src/unix_dgram.cc
index 4c6e9e8..370b1e4 100644
--- a/src/unix_dgram.cc
+++ b/src/unix_dgram.cc
@@ -317,7 +317,7 @@ NAN_METHOD(Send) {
   err = 0;
   if (r == -1) {
     err = -errno;
-    if ((errno == EAGAIN) || (errno == EWOULDBLOCK)) {
+    if ((errno == EAGAIN) || (errno == EWOULDBLOCK) || (errno == ENOBUFS)) {
       watchers_t::iterator iter = watchers.find(fd);
       assert(iter != watchers.end());
       SocketContext* sc = iter->second;
```

**Comment by jbdemonte** [comment]
I confirm this patch works like a charm 👍
