### ISSUE TITLE
Nan::NAN_METHOD_RETURN_TYPE 

### ISSUE THREAD

**Issue by kekobin** [bnoordhuis/node-unix-dgram#51]
hi, there, i use this plugin to send buffer with a sock file, but encount error:    
```
node: ../src/unix_dgram.cc:299: Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Send(Nan::NAN_METHOD_ARGS_TYPE): Assertion `node::Buffer::HasInstance(buf)' failed.
```

is there anyone know why?

**Comment by bnoordhuis** [comment]
You're trying to send something that isn't `instanceof Buffer`. Hard to say more without seeing your code.
