### ISSUE TITLE
2.0.3 causes hangs on Node < 12

### ISSUE THREAD

**Issue by DABH** [bnoordhuis/node-unix-dgram#52]
When I use node-unix-dgram 2.0.2 for my library, everything works fine for Node 6-11 but not for 12, as expected.  However, when I upgrade to 2.0.3, Node 12 works fine but on all previous versions my library's tests hang.  Any idea why this could be the case / what else changed between 2.0.2 and 2.0.3?  Here are some examples of the failures I'm talking about:
https://travis-ci.org/winstonjs/winston-syslog/jobs/597469351
cc @bnoordhuis 
Thanks in advance!

**Comment by bnoordhuis** [comment]
My best guess would be a067d295703ce1edfd1dd7c8d0cb00b012ba0bd2. Can you try reverting that change locally and see if that fixes things for you?

Or try pinning your dependency to this repo at commit 0ae2a61c822f34d686de02792a2630527bb1f135, that's its parent commit and should still work with v12.x.

**Comment by DABH** [comment]
Sorry for the glacial pace of following up.  I tried 2.0.3 again today, just like I had before, and this time encountered no issues.  Since node-unix-dgram I assume this is either due to fixes in Node or in the dependencies like Nan?  In any case, since things are working now I'll go ahead and close the issue, will reopen if this ever crops up again in the future.  Many thanks!
